#!/bin/bash
echo -e "» ----------------------------------------------------------"
echo -e ""
echo -e "» menu          : เรียกดูรายการ"
echo -e "» a             : เพิ่มบัญชี SSH & OpenVPN"
echo -e "» b             : เพิ่มบัญชีทดสอบชั่วคราว"
echo -e "» d             : ลบบัญชี SSH & OpenVPN"
echo -e "» c             : ตรวจสอบ user login"
echo -e "» f             : แสดงบัญชีรายชื่อ SSH & OpenVPN"
echo -e "» g             : ลบบัญชีที่หมดอายุ "
echo -e "» rsq           : Restart server"
echo -e "» reboot        : Reboot VPS"
echo -e "» speedtest     : ทดสอบความเร็ว VPS"
echo -e "» vnstat        : ตรวจสอบแบนวิท"
echo -e "» info          : ข้อมูล"
echo -e "» about         : อ้างอิง"
echo -e "» exit          : ออกจาก SSH"
echo -e ""
echo -e "» สคริปนี้แจกฟรีเท่านั้นนะครับ host true id "
echo -e "» ----------------------------------------------------------"
echo -e "» by sangmander kasang   1 ส.ค. 61"
